# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SULMN
                                 A QGIS plugin
 Ułatwienia do pracy ze standardem SULMN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-01
        copyright            : (C) 2021 by Paweł Krąpiec
        email                : pkrapiec@protnmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SULMN class from file SULMN.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sulmn_ulatwienia import SULMN
    return SULMN(iface)
